apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hortus-clavis.fullname" . }}
  labels:
    {{- include "hortus-clavis.labels" . | nindent 4 }}
type: Opaque
data:
  IAM_JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  IAM_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.secrets.bootstrapAdminPassword | b64enc | quote }}
  IAM_DATABASE_URL: {{ include "hortus-clavis.databaseUrl" . | b64enc | quote }}
  IAM_REDIS_URL: {{ include "hortus-clavis.redisUrl" . | b64enc | quote }}
